name: Spin the Disc
description: For the love of music

url: http://alajarvela.github.com/spinthedisc
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contact
   url: /contact
